# Generated by Django 4.0.4 on 2022-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1993-10-01'),
            preserve_default=False,
        ),
    ]
